# Site settings
title: Santiago Regueiro
email: santi@regueiro.es
author: Santiago Regueiro
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Santiago Regueiro and I am a Technical Engineer in Business Computing Systems from Pontevedra.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.regueiro.es" # the base hostname & protocol for your site

timezone: Europe/Madrid
# Comments
disqus_shortname: regueiro

# Analytics
google_analytics: UA-269183-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: regueiro
stackoverflow_id:
twitter_username: santiregueiro
#google_plus_id: +SantiRegueiro
linkedin_username: santiregueiro
instagram_username: sregueiro
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
encoding: utf-8
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
#permalink:    pretty
permalink:    "/:title"
#paginate:     5
#paginate_path: "/blog/page:num"
sass:
  compressed: true


exclude: ["LICENSE", "README.md"]